### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by nikelborm** [khaled-0/MyuSync#16]
I think it's not too costly too change the name while the project in it's early stages

It's quite confusing to have project with exactly the same name

https://github.com/meeb/tubesync

**Comment by khaled-0** [comment]
Yeah i also noticed that project right after the first release.
I'm still open for suggestion to a more fitting name

**Comment by fessmm** [comment]
ChatGPT:

HarmonyHub – Suggests bringing music into harmony across devices.
PulseSync – Evoking the rhythm of music and the syncing process.
PlaylistFlow – Emphasizes the seamless flow of music between platforms.
TrackLink – Highlighting the connection between your playlists and devices.
EchoSync – Suggests music resonating across platforms.

**Comment by khaled-0** [comment]
> ChatGPT:
> 
> HarmonyHub – Suggests bringing music into harmony across devices. PulseSync – Evoking the rhythm of music and the syncing process. PlaylistFlow – Emphasizes the seamless flow of music between platforms. TrackLink – Highlighting the connection between your playlists and devices. EchoSync – Suggests music resonating across platforms.

lmao i got exact same ones

**Comment by barsikus007** [comment]
TubeSync4A
SyncTube
TubeSyncMobile
iTubeSync
xD

**Comment by trindadedev13** [comment]
KhSynx

**Comment by khaled-0** [comment]
> KhSync KhaledSync

absolutely not.

maybe SyncTube(80% likely) or EchoSync will be what I end up going with. but 

 I'm targeting overtaking the colliding project. unrealistic I know.

**Comment by khaled-0** [comment]
I got some more suggestions from AI.
of which I liked  (most to least)
MyuSync > MeloSync > OtoSync > RyuSync



MyuSync:
- "Myu" comes from "music" (ミュー/myu in Japanese katakana)
- Easy to pronounce and remember
- Has a modern, sleek feel
- Could appeal to anime/Japanese culture fans
- "Myu" sounds cute and friendly

OtoSync:
- "Oto" (音) means "sound" in Japanese
- Clean and simple pronunciation
- Has a professional, tech-focused feel
- Two syllables make it easy to remember
- Common word in Japanese audio/music context

MeloSync:
- "Melo" from "melody" or "melos" (Greek for song/music)
- Universal understanding as it relates to melody
- Clearly communicates music functionality
- Professional and classical feeling
- Easy to understand across different languages

RyuSync:
- "Ryu" (流) means "flow/style" in Japanese
- Dragon (竜/ryu) association gives it strength
- Strong, concise sound
- Unique and memorable
- Good mouth-feel when pronounced

**Comment by fessmm** [comment]
for me it would be between

MyuSync and MeloSync

**Comment by ilker-binzet** [comment]
1. FlowSync
2. OmniSync
3. TubeFlow
4. TubeLink – my favorite
5. LinkSync

**Comment by khaled-0** [comment]
I've decided on 

**MyuSync**

> "Myu" comes from "music" (ミュー/myu in Japanese katakana)
> Easy to pronounce and remember
> Has a modern, sleek feel
> Could appeal to anime/Japanese culture fans
> "Myu" sounds cute and friendly

**Comment by khaled-0** [comment]
> When do you plan to change the repository name and app name?

Before Christmas maybe. I'm working on moving the database from ISAR to ObjectBox
Which cuts the app size by 10mb

**Comment by khaled-0** [comment]
MyuSync lowercase looks confusing 
myusync. Well it is what it is

**Comment by iyxan23** [comment]
copying from the discord thread:

**MyuSync** has this cool word play element that pronounces to "Music" (myu-sic). I think we could make use of this better by something like: **MuSync**? Lowercase version looks better imo: musync

If we were to add the YouTube element into the mix, smth like **Tube MuSync** could work lol

**Comment by iyxan23** [comment]
imagine if tubesync gets renamed twice lmao

**Comment by khaled-0** [comment]
Guys, let's all forget myusync. It'll be Syncara soon
